// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'posts.mapper.dart';

@MappableClass()
class Posts with PostsMappable {
  final int userId;
  final int id;
  final String title;
  final String body;

  Posts(this.userId, this.id, this.title, this.body);
}
